#!/bin/sh

PKG_CONFIG_PATH=/home/jncronin/opt/gk/usr/lib/pkgconfig SDL_CONFIG=/home/jncronin/opt/gk/usr/bin/sdl-config SDL2_CONFIG=/home/jncronin/opt/gk/usr/bin/sdl2-config CC=arm-none-gkos-gcc CXX=arm-none-gkos-g++ ../dosbox-x-dosbox-x-v2024.12.04/configure --host=arm-none-gkos --prefix=/home/jncronin/src/dosboxx-gk --disable-sdlnet --disable-x11 --disable-sdl2test --enable-sdl2 --disable-sdl --disable-sdltest --disable-gamelink --disable-opengl --disable-alsatest --disable-printer --disable-xbrz --enable-scaler-full-line --disable-alsa-midi --disable-mt32 --disable-screenshots --disable-libslirp --disable-libfluidsynth --with-sdl-prefix=/home/jncronin/opt/gk/usr --with-sdl2-prefix=/home/jncronin/opt/gk/usr --with-sdl2-exec-prefix=/home/jncronin/opt/gk/usr --with-sdl-exec-prefix=/home/jncronin/opt/gk/usr SDL2_CONFIG=/home/jncronin/opt/gk/usr/bin/sdl2-config PKG_CONFIG_PATH=/home/jncronin/opt/gk/usr/lib/pkgconfig 


# for v4:

PKG_CONFIG_PATH=/home/jncronin/opt/gkv4/usr/lib/pkgconfig SDL_CONFIG=/home/jncronin/opt/gkv4/usr/bin/sdl-config SDL2_CONFIG=/home/jncronin/opt/gkv4/usr/bin/sdl2-config CC=aarch64-none-gkos-gcc CXX=aarch64-none-gkos-g++ ../dosbox-x/configure --host=aarch64-none-gkos --prefix=/home/jncronin/src/dosboxx-gkv4 --disable-sdlnet --disable-x11 --disable-sdl2test --enable-sdl2 --disable-sdl --disable-sdltest --disable-gamelink --disable-opengl --disable-alsatest --disable-printer --disable-xbrz --enable-scaler-full-line --disable-alsa-midi --disable-mt32 --disable-screenshots --disable-libslirp --disable-libfluidsynth --with-sdl-prefix=/home/jncronin/opt/gkv4/usr --with-sdl2-prefix=/home/jncronin/opt/gkv4/usr --with-sdl2-exec-prefix=/home/jncronin/opt/gkv4/usr --with-sdl-exec-prefix=/home/jncronin/opt/gkv4/usr SDL2_CONFIG=/home/jncronin/opt/gkv4/usr/bin/sdl2-config PKG_CONFIG_PATH=/home/jncronin/opt/gkv4/usr/lib/pkgconfig 

PKG_CONFIG_PATH=/home/jncronin/opt/gkv4/usr/lib/pkgconfig SDL_CONFIG=/home/jncronin/opt/gkv4/usr/bin/sdl-config SDL2_CONFIG=/home/jncronin/opt/gkv4/usr/bin/sdl2-config CC=aarch64-none-gkos-gcc CXX=aarch64-none-gkos-g++ ../dosbox-x/configure --host=aarch64-none-gkos --prefix=/home/jncronin/src/dosboxx-gkv4 --disable-sdlnet --disable-x11 --disable-sdl2test --enable-sdl2 --disable-sdl --disable-sdltest --disable-gamelink --disable-opengl --disable-alsatest --disable-printer --disable-xbrz --enable-scaler-full-line --disable-alsa-midi --disable-screenshots --disable-libslirp --enable-libfluidsynth --with-sdl-prefix=/home/jncronin/opt/gkv4/usr --with-sdl2-prefix=/home/jncronin/opt/gkv4/usr --with-sdl2-exec-prefix=/home/jncronin/opt/gkv4/usr --with-sdl-exec-prefix=/home/jncronin/opt/gkv4/usr SDL2_CONFIG=/home/jncronin/opt/gkv4/usr/bin/sdl2-config PKG_CONFIG_PATH=/home/jncronin/opt/gkv4/usr/lib/pkgconfig 
